export const NODE_ACTIVE_TEXT_EDITOR_NAME = 'Undefined';
export const UNTITLED = 'Untitled';
export const NO_PROJ_NAME = 'Unnamed';
export const ONE_SEC_MILLISECONDS = 1000;
export const ONE_MIN_SECONDS = 60;
export const ONE_MIN_MILLISECONDS = ONE_SEC_MILLISECONDS * ONE_MIN_SECONDS;
export const CONFIG_KEY_DOMAIN = 'iceworks';
export const CONFIG_KEY_SECTION = 'enableViews';
export const CONFIG_KEY_ICEWORKS_ENABLE_VIEWS = `${CONFIG_KEY_DOMAIN}.${CONFIG_KEY_SECTION}`;
