// 资产包协议
// http://iceworks.oss-cn-hangzhou.aliyuncs.com/iceluna/componentList_fusion.json
export default [
  {
    'id': 1,
    'name': '默认',
    'items': [
      {
        'basic_id': 408,
        'id': 828,
        'name': 'Div',
        'title': '层标签',
        'screenshot': null,
        'icon': 'biankuang',
        'is_container': 1,
        'is_layout': 0,
        'parent_rule': null,
        'children_rule': null,
        'tags': null,
        'package': '@ali/iceluna-components-div',
        'export_name': 'Div',
        'sub_name': null,
        'destructuring': 0,
        'main': null,
        'is_show': 1,
        'site_id': 1,
        'dev_mode': 1,
        'description': 'Div',
        'is_open': 0,
        'version': '^0.0.5',
        'category_id': 1,
        'category': '默认',
        'library_id': 1,
        'snippets': [
          {
            'id': 13,
            'name': 'Div容器',
            'screenshot': '',
            'code': '[{\n        "componentName": "Div",\n        "props": {},\n        "children": []\n      }]',
            'basic_id': 408
          }
        ]
      },
      {
        'basic_id': 409,
        'id': 829,
        'name': 'Text',
        'title': '文本',
        'screenshot': null,
        'icon': 'wenben',
        'is_container': 0,
        'is_layout': 0,
        'parent_rule': null,
        'children_rule': null,
        'tags': null,
        'package': '@ali/iceluna-components-text',
        'export_name': 'Text',
        'sub_name': null,
        'destructuring': 0,
        'main': null,
        'is_show': 1,
        'site_id': 1,
        'dev_mode': 1,
        'description': 'Text',
        'is_open': 0,
        'version': '^0.0.2',
        'category_id': 1,
        'category': '默认',
        'library_id': 1,
        'snippets': [
          {
            'id': 12,
            'name': '文本',
            'screenshot': '',
            'code': '[{\n    "componentName": "Text",\n    "props": {\n      "text": "文本"\n    }\n  }]',
            'basic_id': 409
          }
        ]
      },
      {
        'basic_id': 412,
        'id': 832,
        'name': 'Image',
        'title': '图片',
        'screenshot': null,
        'icon': 'picture',
        'is_container': 0,
        'is_layout': 0,
        'parent_rule': null,
        'children_rule': null,
        'tags': null,
        'package': '@ali/iceluna-components-image',
        'export_name': 'Image',
        'sub_name': null,
        'destructuring': 0,
        'main': null,
        'is_show': 1,
        'site_id': 1,
        'dev_mode': 1,
        'description': 'image',
        'is_open': 0,
        'version': '^0.0.2',
        'category_id': 1,
        'category': '默认',
        'library_id': 1,
        'snippets': [
          {
            'id': 9,
            'name': '图片',
            'screenshot': '',
            'code': '{\n    "componentName": "Image",\n    "props": {\n      "src": "https://gw.alicdn.com/tfs/TB1bq04hrr1gK0jSZFDXXb9yVXa-64-72.png",\n      "style": {\n        "width": 60,\n        "height": 67\n      }\n    }\n  }',
            'basic_id': 412
          }
        ]
      },
      {
        'basic_id': 410,
        'id': 830,
        'name': 'A',
        'title': '超链接',
        'screenshot': null,
        'icon': 'lianjie',
        'is_container': 1,
        'is_layout': 0,
        'parent_rule': null,
        'children_rule': null,
        'tags': null,
        'package': '@ali/iceluna-components-a',
        'export_name': 'A',
        'sub_name': null,
        'destructuring': 0,
        'main': null,
        'is_show': 1,
        'site_id': 1,
        'dev_mode': 1,
        'description': 'A',
        'is_open': 0,
        'version': '^0.0.6',
        'category_id': 1,
        'category': '默认',
        'library_id': 1,
        'snippets': [
          {
            'id': 11,
            'name': '超链接',
            'screenshot': '',
            'code': '[{\n    "componentName": "A",\n    "props": {\n      "href": "https://f2e.alibaba-inc.com/",\n      "target": "_blank",\n    },\n    "children": "链接"\n  }]',
            'basic_id': 410
          }
        ]
      },
      {
        'basic_id': 415,
        'id': 839,
        'name': 'Block',
        'title': '区块容器',
        'screenshot': null,
        'icon': 'jihe',
        'is_container': 1,
        'is_layout': 0,
        'parent_rule': null,
        'children_rule': null,
        'tags': '区块,容器',
        'package': null,
        'export_name': null,
        'sub_name': null,
        'destructuring': 0,
        'main': null,
        'is_show': 1,
        'site_id': 1,
        'dev_mode': 1,
        'description': '区块容器组件，用于发送数据请求，绑定数据源，做数据容器',
        'is_open': 0,
        'version': '1.0.0',
        'category_id': 1,
        'category': '默认',
        'library_id': 1,
        'snippets': [
          {
            'id': 0,
            'name': '请拖入该组件',
            'code': '[{"componentName":"Block","props":{}}]'
          }
        ]
      }
    ]
  },
  {
    'id': 3,
    'name': '常用类',
    'items': [
      {
        'basic_id': 215,
        'id': 734,
        'name': 'Grid',
        'title': '栅格',
        'screenshot': null,
        'icon': null,
        'is_container': 1,
        'is_layout': 0,
        'parent_rule': null,
        'children_rule': null,
        'tags': null,
        'package': '@alife/next',
        'export_name': 'Grid',
        'sub_name': null,
        'destructuring': 1,
        'main': null,
        'is_show': 1,
        'site_id': 1,
        'dev_mode': 1,
        'description': null,
        'is_open': 0,
        'version': '1.16.6',
        'category_id': 3,
        'category': '常用类',
        'library_id': 1,
        'snippets': [
          {
            'id': 39,
            'name': '一行三列',
            'screenshot': null,
            'code': '[{\n    "componentName": "Row",\n    "props": {\n      "style": {}\n    },\n    "children": [{\n      "componentName": "Col",\n      "props": {},\n      "children": [{\n        "componentName": "Text",\n        "props": {\n          "text": "第一列"\n        }\n      }]\n    }, {\n      "componentName": "Col",\n      "props": {},\n      "children": [{\n        "componentName": "Text",\n        "props": {\n          "text": "第二列"\n        }\n      }]\n    }, {\n      "componentName": "Col",\n      "props": {},\n      "children": [{\n        "componentName": "Text",\n        "props": {\n          "text": "第三列"\n        }\n      }]\n    }]\n  }]',
            'basic_id': 215
          },
          {
            'id': 38,
            'name': '一行两列',
            'screenshot': null,
            'code': '[{\n    "componentName": "Row",\n    "props": {\n      "style": {}\n    },\n    "children": [{\n      "componentName": "Col",\n      "props": {},\n      "children": [{\n        "componentName": "Text",\n        "props": {\n          "text": "第一列"\n        }\n      }]\n    }, {\n      "componentName": "Col",\n      "props": {},\n      "children": [{\n        "componentName": "Text",\n        "props": {\n          "text": "第二列"\n        }\n      }]\n    }]\n  }]',
            'basic_id': 215
          }
        ]
      },
      {
        'basic_id': 201,
        'id': 748,
        'name': 'Button',
        'title': '按钮',
        'screenshot': 'https://gw.alicdn.com/tfs/TB13JGeeAT2gK0jSZFkXXcIQFXa-254-53.png',
        'icon': null,
        'is_container': 1,
        'is_layout': 0,
        'parent_rule': null,
        'children_rule': null,
        'tags': null,
        'package': '@alife/next',
        'export_name': 'Button',
        'sub_name': '',
        'destructuring': 1,
        'main': null,
        'is_show': 1,
        'site_id': 1,
        'dev_mode': 1,
        'description': '标准fusion组件按钮',
        'is_open': 0,
        'version': '1.16.6',
        'category_id': 3,
        'category': '常用类',
        'library_id': 1,
        'snippets': [
          {
            'id': 6,
            'name': '主要按钮',
            'screenshot': '',
            'code': '[{\n    "componentName": "Button",\n    "props": {\n      "type": "primary"\n    },\n    "children": "确定"\n  }]',
            'basic_id': 201
          },
          {
            'id': 40,
            'name': '次要按钮',
            'screenshot': null,
            'code': '[{\n    "componentName": "Button",\n    "props": {\n      "type": "secondary"\n    },\n    "children": "确定"\n  }]',
            'basic_id': 201
          },
          {
            'id': 41,
            'name': '普通按钮',
            'screenshot': null,
            'code': '[{\n    "componentName": "Button",\n    "props": {\n      "type": "normal"\n    },\n    "children": "确定"\n  }]',
            'basic_id': 201
          },
          {
            'id': 8,
            'name': '按钮组',
            'screenshot': '',
            'code': '[{\n    "componentName": "ButtonGroup",\n    "props": {},\n    "children": [{\n      "componentName": "Button",\n      "props": {\n        "type": "primary",\n        "style": {\n          "margin": "0 5px 0 5px"\n        }\n      },\n      "children": "确定"\n    }, {\n      "componentName": "Button",\n      "props": {\n        "type": "normal",\n        "style": {\n          "margin": "0 5px 0 5px"\n        }\n      },\n      "children": "取消"\n    }]\n  }]',
            'basic_id': 201
          }
        ]
      },
      {
        'basic_id': 216,
        'id': 733,
        'name': 'Icon',
        'title': '图标',
        'screenshot': null,
        'icon': null,
        'is_container': 0,
        'is_layout': 0,
        'parent_rule': null,
        'children_rule': null,
        'tags': null,
        'package': '@alife/next',
        'export_name': 'Icon',
        'sub_name': null,
        'destructuring': 1,
        'main': null,
        'is_show': 1,
        'site_id': 1,
        'dev_mode': 1,
        'description': null,
        'is_open': 0,
        'version': '1.16.6',
        'category_id': 3,
        'category': '常用类',
        'library_id': 1,
        'snippets': [
          {
            'id': 14,
            'name': '图标',
            'screenshot': '',
            'code': '[{\n    "componentName": "Icon",\n    "props": {\n      "type": "help",\n      "size": "large",\n      "style": {\n        "color": "#9b9b9b"\n      }\n    }\n  }]',
            'basic_id': 216
          }
        ]
      },
    ]
  },
  {
    'id': 4,
    'name': '导航类',
    'items': [
      {
        'basic_id': 225,
        'id': 724,
        'name': 'Pagination',
        'title': '翻页器',
        'screenshot': null,
        'icon': null,
        'is_container': 0,
        'is_layout': 0,
        'parent_rule': null,
        'children_rule': null,
        'tags': null,
        'package': '@alife/next',
        'export_name': 'Pagination',
        'sub_name': null,
        'destructuring': 1,
        'main': null,
        'is_show': 1,
        'site_id': 1,
        'dev_mode': 1,
        'description': null,
        'is_open': 0,
        'version': '1.16.6',
        'category_id': 4,
        'category': '导航类',
        'library_id': 1,
        'snippets': [
          {
            'id': 49,
            'name': '普通翻页器',
            'screenshot': null,
            'code': '[ {\n    "componentName": "Pagination",\n    "props": {\n      "shape": "normal",\n      "type": "normal",\n      "size": "medium"\n    }\n  }]',
            'basic_id': 225
          }
        ]
      }
    ]
  },
  {
    'id': 5,
    'name': '表单类',
    'items': [
      {
        'basic_id': 214,
        'id': 735,
        'name': 'Form',
        'title': '表单',
        'screenshot': null,
        'icon': null,
        'is_container': 1,
        'is_layout': 0,
        'parent_rule': null,
        'children_rule': null,
        'tags': null,
        'package': '@alife/next',
        'export_name': 'Form',
        'sub_name': null,
        'destructuring': 1,
        'main': null,
        'is_show': 1,
        'site_id': 1,
        'dev_mode': 1,
        'description': null,
        'is_open': 0,
        'version': '1.16.6',
        'category_id': 5,
        'category': '表单类',
        'library_id': 1,
        'snippets': [
          {
            'id': 66,
            'name': '基本表单',
            'screenshot': null,
            'code': '{\n    "componentName": "Form",\n    "props": {\n      "labelCol": 4,\n      },\n    "children": [{\n      "componentName": "FormItem",\n      "props": {\n        "label": "姓名：",\n        "name": "name",\n        "initValue": "李雷"\n      },\n      "children": [{\n        "componentName": "Input",\n        "props": {\n          "placeholder": "请输入",\n          "size": "medium"\n        }\n      }]\n    }, {\n      "componentName": "FormItem",\n      "props": {\n        "label": "年龄：",\n        "name": "age",\n        "initValue": "22"\n      },\n      "children": [{\n        "componentName": "NumberPicker",\n        "props": {\n          "size": "medium",\n          "type": "normal"\n        }\n      }]\n    }, {\n      "componentName": "FormItem",\n      "props": {\n        "label": "性别：",\n        "name": "sex"\n      },\n      "children": [{\n        "componentName": "RadioGroup",\n        "props": {\n          "dataSource": [{\n            "label": "男",\n            "value": "boy"\n          }, {\n            "label": "女",\n            "value": "girl"\n          }]\n        }\n      }]\n    }, {\n      "componentName": "FormItem",\n      "props": {\n        "label": "职业：",\n        "name": "profession"\n      },\n      "children": [{\n        "componentName": "Select",\n        "props": {\n          "dataSource": [{\n            "label": "教师",\n            "value": "t"\n          }, {\n            "label": "医生",\n            "value": "d"\n          }, {\n            "label": "歌手",\n            "value": "s"\n          }]\n        }\n      }]\n    }, {\n      "componentName": "FormItem",\n      "props": {\n        "label": "是否已婚：",\n        "name": "married"\n      },\n      "children": [{\n        "componentName": "Checkbox",\n        "props": {\n          "label": "已婚"\n        }\n      }]\n    }, {\n      "componentName": "FormItem",\n      "props": {\n        "label": "工作经历：",\n        "name": "work"\n      },\n      "children": [{\n        "componentName": "RangePicker",\n        "props": {}\n      }]\n    }, {\n      "componentName": "ButtonGroup",\n      "props": {},\n      "children": [{\n        "componentName": "Button",\n        "props": {\n          "type": "primary",\n          "style": {\n            "margin": "0 5px 0 5px"\n          },\n          "htmlType": "submit"\n        },\n        "children": "提交"\n      }, {\n        "componentName": "Button",\n        "props": {\n          "type": "normal",\n          "style": {\n            "margin": "0 5px 0 5px"\n          },\n          "htmlType": "reset"\n        },\n        "children": "重置"\n      }]\n    }]\n  }',
            'basic_id': 214
          }
        ]
      },
      {
        'basic_id': 217,
        'id': 732,
        'name': 'Input',
        'title': '输入框',
        'screenshot': null,
        'icon': null,
        'is_container': 0,
        'is_layout': 0,
        'parent_rule': null,
        'children_rule': null,
        'tags': null,
        'package': '@alife/next',
        'export_name': 'Input',
        'sub_name': null,
        'destructuring': 1,
        'main': null,
        'is_show': 1,
        'site_id': 1,
        'dev_mode': 1,
        'description': null,
        'is_open': 0,
        'version': '1.16.6',
        'category_id': 5,
        'category': '表单类',
        'library_id': 1,
        'snippets': [
          {
            'id': 15,
            'name': '输入框',
            'screenshot': '',
            'code': '[{\n    "componentName": "Input",\n    "props": {\n      "placeholder": "请输入",\n      "size": "medium",\n    }\n  }]',
            'basic_id': 217
          },
          {
            'id': 16,
            'name': '文本域',
            'screenshot': null,
            'code': '[{\n    "componentName": "TextArea",\n    "props": {\n      "placeholder": "请输入"\n    }\n  }]',
            'basic_id': 217
          },
          {
            'id': 17,
            'name': '输入框组',
            'screenshot': null,
            'code': '[{\n    "componentName": "InputGroup",\n    "props": {\n      "addonBefore": [{\n        "componentName": "Select",\n        "props": {\n          "dataSource": "{{[{label:\'https\',value:\'https\'},{lable:\'http\',value:\'http\'}]}}"\n        }\n      }],\n      "addonAfter": [{\n        "componentName": "Button",\n        "props": {\n          "type": "primary"\n        },\n        "children": "搜索"\n      }]\n    },\n    "children": [{\n      "componentName": "Input",\n      "props": {\n        "placeholder": "请输入",\n        "size": "medium",\n        "style": {\n          "width": "100%"\n        }\n      }\n    }]\n  }]',
            'basic_id': 217
          }
        ]
      },
      {
        'basic_id': 208,
        'id': 740,
        'name': 'Checkbox',
        'title': '复选按钮',
        'screenshot': null,
        'icon': null,
        'is_container': 0,
        'is_layout': 0,
        'parent_rule': null,
        'children_rule': null,
        'tags': null,
        'package': '@alife/next',
        'export_name': 'Checkbox',
        'sub_name': null,
        'destructuring': 1,
        'main': null,
        'is_show': 1,
        'site_id': 1,
        'dev_mode': 1,
        'description': null,
        'is_open': 0,
        'version': '1.16.6',
        'category_id': 5,
        'category': '表单类',
        'library_id': 1,
        'snippets': [
          {
            'id': 18,
            'name': '复选按钮',
            'screenshot': null,
            'code': '[{\n    "componentName": "Checkbox",\n    "props": {\n      "label": "Checked"\n    }\n  }]',
            'basic_id': 208
          },
          {
            'id': 19,
            'name': '复选按钮组',
            'screenshot': null,
            'code': '[{\n        "componentName": "CheckboxGroup",\n        "props": {\n          "dataSource": [{\n            "label": "apple",\n            "value": "apple"\n          }, {\n            "label": "pear",\n            "value": "pear"\n          }, {\n            "label": "orange",\n            "value": "orange"\n          }]\n        }\n      }]',
            'basic_id': 208
          }
        ]
      },
      {
        'basic_id': 228,
        'id': 720,
        'name': 'Radio',
        'title': '单选框',
        'screenshot': null,
        'icon': null,
        'is_container': 1,
        'is_layout': 0,
        'parent_rule': null,
        'children_rule': null,
        'tags': null,
        'package': '@alife/next',
        'export_name': 'Radio',
        'sub_name': null,
        'destructuring': 1,
        'main': null,
        'is_show': 1,
        'site_id': 1,
        'dev_mode': 1,
        'description': null,
        'is_open': 0,
        'version': '1.16.6',
        'category_id': 5,
        'category': '表单类',
        'library_id': 1,
        'snippets': [
          {
            'id': 20,
            'name': '基本单选',
            'screenshot': null,
            'code': '[{\n        "componentName": "RadioGroup",\n        "props": {\n          "dataSource": [{\n            "label": "apple",\n            "value": "apple"\n          }, {\n            "label": "pear",\n            "value": "pear"\n          }, {\n            "label": "orange",\n            "value": "orange"\n          }]\n        }\n      }]',
            'basic_id': 228
          },
          {
            'id': 21,
            'name': '按钮单选',
            'screenshot': null,
            'code': '[{\n    "componentName": "RadioGroup",\n    "props": {\n      "shape": "button",\n      "dataSource": "{{[\'apple\', \'pear\', \'orange\']}}"\n    }\n  }]',
            'basic_id': 228
          }
        ]
      },
      {
        'basic_id': 232,
        'id': 717,
        'name': 'Select',
        'title': '选择器',
        'screenshot': null,
        'icon': null,
        'is_container': 0,
        'is_layout': 0,
        'parent_rule': null,
        'children_rule': null,
        'tags': null,
        'package': '@alife/next',
        'export_name': 'Select',
        'sub_name': null,
        'destructuring': 1,
        'main': null,
        'is_show': 1,
        'site_id': 1,
        'dev_mode': 1,
        'description': null,
        'is_open': 0,
        'version': '1.16.6',
        'category_id': 5,
        'category': '表单类',
        'library_id': 1,
        'snippets': [
          {
            'id': 22,
            'name': '基本选择器',
            'screenshot': null,
            'code': '[{\n        "componentName": "Select",\n        "props": {\n          "dataSource": [{\n            "label": "lack",\n            "value": "lack"\n          }, {\n            "label": "rose",\n            "value": "rose"\n          }, {\n            "label": "dava",\n            "value": "dava"\n          }]\n        }\n      }]',
            'basic_id': 232
          },
          {
            'id': 24,
            'name': '自动完成',
            'screenshot': null,
            'code': '{\n    "componentName": "AutoComplete",\n    "props": {\n      "dataSource": ["Lucy King", "Lily King", "Jim Green"]\n    }\n  }',
            'basic_id': 232
          },
          {
            'id': 25,
            'name': '分组选择器',
            'screenshot': null,
            'code': '{\n    "componentName": "Select",\n    "props": {\n      "placeholder": "请选择",\n      "dataSource": [{\n        "label": "label1",\n        "children": [{\n          "label": "label1-1",\n          "value": "text1-1"\n        }]\n      }, {\n        "label": "label2",\n        "children": [{\n          "label": "label2-1",\n          "value": "text2-1"\n        }]\n      }]\n    },\n    "children": []\n  }',
            'basic_id': 232
          }
        ]
      },
      {
        'basic_id': 244,
        'id': 705,
        'name': 'TreeSelect',
        'title': '树形选择器',
        'screenshot': null,
        'icon': null,
        'is_container': 0,
        'is_layout': 0,
        'parent_rule': null,
        'children_rule': null,
        'tags': null,
        'package': '@alife/next',
        'export_name': 'TreeSelect',
        'sub_name': null,
        'destructuring': 1,
        'main': null,
        'is_show': 1,
        'site_id': 1,
        'dev_mode': 1,
        'description': null,
        'is_open': 0,
        'version': '1.16.6',
        'category_id': 5,
        'category': '表单类',
        'library_id': 1,
        'snippets': [
          {
            'id': 68,
            'name': '基本树型选择',
            'screenshot': null,
            'code': '{\n    "componentName": "TreeSelect",\n    "props": {\n      "dataSource": [{\n        "label": "Component",\n        "value": "1",\n        "children": [{\n          "label": "Form",\n          "value": "2",\n          "children": [{\n            "label": "Input",\n            "value": "4"\n          }, {\n            "label": "Select",\n            "value": "5",\n            "disabled": true\n          }]\n        }, {\n          "label": "Display",\n          "value": "3",\n          "children": [{\n            "label": "Table",\n            "value": "6"\n          }]\n        }]\n      }],\n      "autoWidth": false\n    },\n    "children": []\n  }',
            'basic_id': 244
          }
        ]
      },
      {
        'basic_id': 205,
        'id': 745,
        'name': 'CascaderSelect',
        'title': '级联选择',
        'screenshot': null,
        'icon': null,
        'is_container': 0,
        'is_layout': 0,
        'parent_rule': null,
        'children_rule': null,
        'tags': null,
        'package': '@alife/next',
        'export_name': 'CascaderSelect',
        'sub_name': null,
        'destructuring': 1,
        'main': null,
        'is_show': 1,
        'site_id': 1,
        'dev_mode': 1,
        'description': null,
        'is_open': 0,
        'version': '1.16.6',
        'category_id': 5,
        'category': '表单类',
        'library_id': 1,
        'snippets': [
          {
            'id': 63,
            'name': '级联选择',
            'screenshot': null,
            'code': '{\n    "componentName": "CascaderSelect",\n    "props": {\n      "dataSource": [{\n        "value": "2974",\n        "label": "西安",\n        "children": [{\n          "value": "2975",\n          "label": "西安市",\n          "disabled": true\n        }, {\n          "value": "2976",\n          "label": "高陵县",\n          "checkboxDisabled": true\n        }, {\n          "value": "2977",\n          "label": "蓝田县"\n        }, {\n          "value": "2978",\n          "label": "户县"\n        }, {\n          "value": "2979",\n          "label": "周至县"\n        }, {\n          "value": "4208",\n          "label": "灞桥区"\n        }, {\n          "value": "4209",\n          "label": "长安区"\n        }, {\n          "value": "4210",\n          "label": "莲湖区"\n        }, {\n          "value": "4211",\n          "label": "临潼区"\n        }, {\n          "value": "4212",\n          "label": "未央区"\n        }, {\n          "value": "4213",\n          "label": "新城区"\n        }, {\n          "value": "4214",\n          "label": "阎良区"\n        }, {\n          "value": "4215",\n          "label": "雁塔区"\n        }, {\n          "value": "4388",\n          "label": "碑林区"\n        }, {\n          "value": "610127",\n          "label": "其它区"\n        }]\n      }],\n      "hasBorder": true,\n      "defaultVisible": false\n    }\n  }',
            'basic_id': 205
          }
        ]
      },
      {
        'basic_id': 211,
        'id': 738,
        'name': 'DatePicker',
        'title': '日期选择框',
        'screenshot': null,
        'icon': null,
        'is_container': 0,
        'is_layout': 0,
        'parent_rule': null,
        'children_rule': null,
        'tags': null,
        'package': '@alife/next',
        'export_name': 'DatePicker',
        'sub_name': null,
        'destructuring': 1,
        'main': null,
        'is_show': 1,
        'site_id': 1,
        'dev_mode': 1,
        'description': null,
        'is_open': 0,
        'version': '1.16.6',
        'category_id': 5,
        'category': '表单类',
        'library_id': 1,
        'snippets': [
          {
            'id': 26,
            'name': '日期选择框',
            'screenshot': null,
            'code': '[{\n    "componentName": "DatePicker",\n    "props": {}\n  }]',
            'basic_id': 211
          },
          {
            'id': 27,
            'name': '月份选择框',
            'screenshot': null,
            'code': '[{\n    "componentName": "MonthPicker",\n    "props": {}\n  }]',
            'basic_id': 211
          },
          {
            'id': 29,
            'name': '年份选择框',
            'screenshot': null,
            'code': '[{\n    "componentName": "YearPicker",\n    "props": {}\n  }]',
            'basic_id': 211
          },
          {
            'id': 28,
            'name': '区间选择框',
            'screenshot': null,
            'code': '[{\n    "componentName": "RangePicker",\n    "props": {}\n  }]',
            'basic_id': 211
          }
        ]
      },
      {
        'basic_id': 242,
        'id': 707,
        'name': 'TimePicker',
        'title': '时间选择框',
        'screenshot': null,
        'icon': null,
        'is_container': 0,
        'is_layout': 0,
        'parent_rule': null,
        'children_rule': null,
        'tags': null,
        'package': '@alife/next',
        'export_name': 'TimePicker',
        'sub_name': null,
        'destructuring': 1,
        'main': null,
        'is_show': 1,
        'site_id': 1,
        'dev_mode': 1,
        'description': null,
        'is_open': 0,
        'version': '1.16.6',
        'category_id': 5,
        'category': '表单类',
        'library_id': 1,
        'snippets': [
          {
            'id': 30,
            'name': '时间选择框',
            'screenshot': null,
            'code': '[{\n    "componentName": "TimePicker",\n    "props": {}\n  }]',
            'basic_id': 242
          }
        ]
      },
      {
        'basic_id': 223,
        'id': 726,
        'name': 'NumberPicker',
        'title': '数字输入框',
        'screenshot': null,
        'icon': null,
        'is_container': 0,
        'is_layout': 0,
        'parent_rule': null,
        'children_rule': null,
        'tags': null,
        'package': '@alife/next',
        'export_name': 'NumberPicker',
        'sub_name': null,
        'destructuring': 1,
        'main': null,
        'is_show': 1,
        'site_id': 1,
        'dev_mode': 1,
        'description': null,
        'is_open': 0,
        'version': '1.16.6',
        'category_id': 5,
        'category': '表单类',
        'library_id': 1,
        'snippets': [
          {
            'id': 31,
            'name': '普通数字输入框',
            'screenshot': null,
            'code': '[{\n    "componentName": "NumberPicker",\n    "props": {\n      "size": "medium",\n      "type": "normal"\n    }\n  }]',
            'basic_id': 223
          },
          {
            'id': 32,
            'name': '内联数字输入框',
            'screenshot': null,
            'code': '[{\n    "componentName": "NumberPicker",\n    "props": {\n      "size": "medium",\n      "type": "inline"\n    }\n  }]',
            'basic_id': 223
          }
        ]
      },
      {
        'basic_id': 236,
        'id': 713,
        'name': 'Switch',
        'title': '开关',
        'screenshot': null,
        'icon': null,
        'is_container': 0,
        'is_layout': 0,
        'parent_rule': null,
        'children_rule': null,
        'tags': null,
        'package': '@alife/next',
        'export_name': 'Switch',
        'sub_name': null,
        'destructuring': 1,
        'main': null,
        'is_show': 1,
        'site_id': 1,
        'dev_mode': 1,
        'description': null,
        'is_open': 0,
        'version': '1.16.6',
        'category_id': 5,
        'category': '表单类',
        'library_id': 1,
        'snippets': [
          {
            'id': 33,
            'name': '开关',
            'screenshot': null,
            'code': '[{\n    "componentName": "Switch",\n    "props": {\n      "checkedChildren": "开",\n      "unCheckedChildren": "关"\n    }\n  }]',
            'basic_id': 236
          }
        ]
      },
      {
        'basic_id': 229,
        'id': 721,
        'name': 'Range',
        'title': '区段选择器',
        'screenshot': null,
        'icon': null,
        'is_container': 0,
        'is_layout': 0,
        'parent_rule': null,
        'children_rule': null,
        'tags': null,
        'package': '@alife/next',
        'export_name': 'Range',
        'sub_name': null,
        'destructuring': 1,
        'main': null,
        'is_show': 1,
        'site_id': 1,
        'dev_mode': 1,
        'description': null,
        'is_open': 0,
        'version': '1.16.6',
        'category_id': 5,
        'category': '表单类',
        'library_id': 1,
        'snippets': [
          {
            'id': 34,
            'name': '区段选择器',
            'screenshot': null,
            'code': '[{\n    "componentName": "Range",\n    "props": {\n      "min": 0,\n      "max": 10,\n      "marks": true,\n      "fixedWidth": true,\n      "defaultValue": 6\n    }\n  }]',
            'basic_id': 229
          }
        ]
      },
      {
        'basic_id': 231,
        'id': 719,
        'name': 'Rating',
        'title': '评分',
        'screenshot': null,
        'icon': null,
        'is_container': 0,
        'is_layout': 0,
        'parent_rule': null,
        'children_rule': null,
        'tags': null,
        'package': '@alife/next',
        'export_name': 'Rating',
        'sub_name': null,
        'destructuring': 1,
        'main': null,
        'is_show': 1,
        'site_id': 1,
        'dev_mode': 1,
        'description': null,
        'is_open': 0,
        'version': '1.16.6',
        'category_id': 5,
        'category': '表单类',
        'library_id': 1,
        'snippets': [
          {
            'id': 50,
            'name': '评分',
            'screenshot': null,
            'code': '[{\n    "componentName": "Rating",\n    "props": {\n      "size": "medium",\n      "defaultValue": 4\n    }\n  }]',
            'basic_id': 231
          }
        ]
      },
      {
        'basic_id': 240,
        'id': 709,
        'name': 'Transfer',
        'title': '穿梭框',
        'screenshot': null,
        'icon': null,
        'is_container': 0,
        'is_layout': 0,
        'parent_rule': null,
        'children_rule': null,
        'tags': null,
        'package': '@alife/next',
        'export_name': 'Transfer',
        'sub_name': null,
        'destructuring': 1,
        'main': null,
        'is_show': 1,
        'site_id': 1,
        'dev_mode': 1,
        'description': null,
        'is_open': 0,
        'version': '1.16.6',
        'category_id': 5,
        'category': '表单类',
        'library_id': 1,
        'snippets': [
          {
            'id': 67,
            'name': '基本穿梭框',
            'screenshot': null,
            'code': '{\n    "componentName": "Transfer",\n    "props": {\n      "dataSource": [{\n        "label": "content1",\n        "value": "content1"\n      }, {\n        "label": "content2",\n        "value": "content2"\n      }, {\n        "label": "content3",\n        "value": "content3"\n      }]\n    }\n  }',
            'basic_id': 240
          }
        ]
      },
      {
        'basic_id': 245,
        'id': 704,
        'name': 'Upload',
        'title': '上传组件',
        'screenshot': null,
        'icon': null,
        'is_container': 1,
        'is_layout': 0,
        'parent_rule': null,
        'children_rule': null,
        'tags': null,
        'package': '@alife/next',
        'export_name': 'Upload',
        'sub_name': null,
        'destructuring': 1,
        'main': null,
        'is_show': 1,
        'site_id': 1,
        'dev_mode': 1,
        'description': null,
        'is_open': 0,
        'version': '1.16.6',
        'category_id': 5,
        'category': '表单类',
        'library_id': 1,
        'snippets': [
          {
            'id': 35,
            'name': '基础上传',
            'screenshot': null,
            'code': '[{\n    "componentName": "Upload",\n    "props": {\n      "action": "https://www.easy-mock.com/mock/5b713974309d0d7d107a74a3/alifd/upload",\n      "multiple": true,\n      "style": {\n        "display": "inline-block"\n      }\n    },\n    "children": [{\n      "componentName": "Button",\n      "props": {\n        "type": "primary"\n      },\n      "children": "上传文件"\n    }]\n  }]',
            'basic_id': 245
          },
          {
            'id': 36,
            'name': '卡片上传',
            'screenshot': null,
            'code': '[{\n    "componentName": "Upload",\n    "props": {\n      "action": "https://www.easy-mock.com/mock/5b713974309d0d7d107a74a3/alifd/upload",\n      "multiple": true,\n      "style": {\n        "display": "inline-block"\n      },\n      "shape": "card",\n      "useDataURL": false\n    },\n    "children": "上传图片"\n  }]',
            'basic_id': 245
          },
          {
            'id': 37,
            'name': '拖拽上传',
            'screenshot': null,
            'code': '[{\n    "componentName": "UploadDragger",\n    "props": {\n      "listType": "image",\n      "accept": "image/png, image/jpg, image/jpeg, image/gif, image/bmp"\n    }\n  }]',
            'basic_id': 245
          }
        ]
      },
      {
        'basic_id': 230,
        'id': 718,
        'name': 'Search',
        'title': '搜索',
        'screenshot': null,
        'icon': null,
        'is_container': 0,
        'is_layout': 0,
        'parent_rule': null,
        'children_rule': null,
        'tags': null,
        'package': '@alife/next',
        'export_name': 'Search',
        'sub_name': null,
        'destructuring': 1,
        'main': null,
        'is_show': 1,
        'site_id': 1,
        'dev_mode': 1,
        'description': null,
        'is_open': 0,
        'version': '1.16.6',
        'category_id': 5,
        'category': '表单类',
        'library_id': 1,
        'snippets': [
          {
            'id': 51,
            'name': '搜索框',
            'screenshot': null,
            'code': '[{\n    "componentName": "Search",\n    "props": {\n      "type": "primary"\n    }\n  }]',
            'basic_id': 230
          }
        ]
      }
    ]
  },
  {
    'id': 6,
    'name': '数据展示',
    'items': [
      {
        'basic_id': 238,
        'id': 712,
        'name': 'Table',
        'title': '表格',
        'screenshot': null,
        'icon': null,
        'is_container': 0,
        'is_layout': 0,
        'parent_rule': null,
        'children_rule': null,
        'tags': null,
        'package': '@alife/next',
        'export_name': 'Table',
        'sub_name': null,
        'destructuring': 1,
        'main': null,
        'is_show': 1,
        'site_id': 1,
        'dev_mode': 1,
        'description': null,
        'is_open': 0,
        'version': '1.16.6',
        'category_id': 6,
        'category': '数据展示',
        'library_id': 1,
        'snippets': [
          {
            'id': 52,
            'name': '基础表格',
            'screenshot': null,
            'code': '{\n    "componentName": "Table",\n    "props": {\n      "hasBorder": true,\n      "hasHeader": true,\n      "dataSource": [{\n        "name": "Jack",\n        "age": 22\n      }, {\n        "name": "Rose",\n        "age": 24\n      }]\n    },\n    "children": [{\n      "componentName": "TableColumn",\n      "props": {\n        "title": "姓名",\n        "dataIndex": "name"\n      }\n    }, {\n      "componentName": "TableColumn",\n      "props": {\n        "title": "年龄",\n        "dataIndex": "age"\n      }\n    }]\n  }',
            'basic_id': 238
          }
        ]
      },
      {
        'basic_id': 207,
        'id': 742,
        'name': 'Card',
        'title': '卡片',
        'screenshot': null,
        'icon': null,
        'is_container': 1,
        'is_layout': 0,
        'parent_rule': null,
        'children_rule': null,
        'tags': null,
        'package': '@alife/next',
        'export_name': 'Card',
        'sub_name': null,
        'destructuring': 1,
        'main': null,
        'is_show': 1,
        'site_id': 1,
        'dev_mode': 1,
        'description': null,
        'is_open': 0,
        'version': '1.16.6',
        'category_id': 6,
        'category': '数据展示',
        'library_id': 1,
        'snippets': [
          {
            'id': 70,
            'name': '基本卡片',
            'screenshot': null,
            'code': '{\n    "componentName": "Card",\n    "props": {\n      "title": "标题",\n      "subTitle": "副标题",\n      "extra": "附加内容"\n    },\n    "children": []\n  }',
            'basic_id': 207
          }
        ]
      },
    ]
  }
]