name: Extension Auto Publisher

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: https://registry.npmjs.org/
      - run: npm i
      - run: npm i -g vsce
      - run: npm run publish:extension
        env:
          VSCE_TOKEN: ${{secrets.VSCE_TOKEN}}